workerpool:
  workers: 5
  job_limit: 100
  job_interval: 60s
  max_retries: 3
  timeout: 3s
  error_probability: 0.1

redis:
  address: "redis:6379"
  dial_timeout: 10s
  read_timeout: 5s
  write_timeout: 5s
  pool_size: 20
  min_idle_conns: 5
  pool_timeout: 10s
  idle_timeout: 10m
  max_retries: 5
  min_retry_backoff: 100ms
  max_retry_backoff: 1s
  queue_name: "jobs"

server:
  address: app
  port: 8080
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 30s
  idle_timeout: 60s